server.port: 8081

spring:
  application.name: book-reviews-spring-aws
  output.ansi.enabled: always
  datasource:
    url: jdbc:h2:mem:bookreviewtestdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2.console:
    enabled: true
    path: /h2